require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 2.7.4
  Include:
    - '**/*.rb'
  Exclude:
    - 'Gemfile.lock'

Naming/FileName:
  Exclude:
    - 'Gemfile'