apiVersion: v1
kind: Service
metadata:
  labels:
    app: testbed
  name: web             # hatcher-umich magic name for auto-magic DNS entry
spec:
  ports:
    - port: 80          # static node port (virtual or physical machine)
      protocol: TCP
      targetPort: 3000  # container port e.g. deployment/testbed
  selector:
    app: testbed
  type: LoadBalancer