name: CI

on:
  push:

  pull_request:

  workflow_dispatch:

env:
  MARIADB_USER: ihs
  MARIADB_PASSWORD: password
  MARIADB_DATABASE: ihs
  INDEPENDENT_HANDLE_SERVER_PREFIX: IHS
  INTEGRATION: "1"
  HS_REST_URL: https://localhost:8000/api/handles
  HS_PREFIX: IHS
  HS_USER: 300:IHS/IHS
  HS_SECKEY: password
  HS_SSL_VERIFY: "0"

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    services:
      ihs:
        image: ghcr.io/mlibrary/handle_rest/ihs-handle-server:latest
        env:
          MARIADB_HOST: mysql
          MARIADB_USER: ihs
          MARIADB_PASSWORD: password
          MARIADB_DATABASE: ihs
          INDEPENDENT_HANDLE_SERVER_PREFIX: IHS
        ports:
          - 2641:2641/tcp
          - 2641:2641/udp
          - 8000:8000/tcp
      mysql:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: password
          MARIADB_USER: ihs
          MARIADB_PASSWORD: password
          MARIADB_ROOT_HOST: localhost
          MARIADB_MYSQL_LOCALHOST_USER: non_empty_value
          MARIADB_DATABASE: ihs
        ports:
          - 3306:3306/tcp

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        # uses: ruby/setup-ruby@v1
        uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Wait For HTTP Service
        run: ./bin/wait-for-http-service.sh http://localhost:8000
      - name: Run CI - lint { standard, rubocop } and tests { spec }
        run: bundle exec rake
